import { Inter, Bitter, Fira_Code } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const bitter = Bitter({ subsets: ["latin"] });
const firaCode = Fira_Code({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bitter.className}>
        <main className={`p-1 md:p-4 box-border ${bitter.className}`}>
          {children}
        </main>
      </body>
    </html>
  );
}
